// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class Book
{
    public string ISBN { get; set; }

    public string BookTitle { get; set; }

    public string BookAuthor { get; set; }

    public string YearOfPublic { get; set; }

    public string Publisher { get; set; }

    public int NoOfCopies { get; set; }

    public string ImageURLS { get; set; }

    public string ImageURLM { get; set; }

    public string ImageURLL { get; set; }
}