// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class BorrowHistory
{
    public int BorrowId { get; set; }

    public int BookInventoryId { get; set; }

    public int BorrowByUserId { get; set; }

    public DateTime DateBorrow { get; set; }

    public DateTime? DateReturn { get; set; }

    public DateTime DateExpectedReturn { get; set; }
}