// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

public partial class EdtBookingContext : DbContext
{
    public EdtBookingContext(DbContextOptions<EdtBookingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BookInventory> BookInventories { get; set; }

    public virtual DbSet<BorrowHistory> BorrowHistories { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<vwAvailableBook> vwAvailableBooks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.ISBN);

            entity.Property(e => e.ISBN)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.BookAuthor)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.BookTitle)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.ImageURLL)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.ImageURLM)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.ImageURLS)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.NoOfCopies).HasDefaultValue(1);
            entity.Property(e => e.Publisher)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.YearOfPublic)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BookInventory>(entity =>
        {
            entity.ToTable("BookInventory");

            entity.Property(e => e.CopiesNumber).HasDefaultValue(1);
            entity.Property(e => e.ISBN)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BorrowHistory>(entity =>
        {
            entity.HasKey(e => e.BorrowId);

            entity.ToTable("BorrowHistory");

            entity.Property(e => e.DateBorrow).HasColumnType("datetime");
            entity.Property(e => e.DateExpectedReturn).HasColumnType("datetime");
            entity.Property(e => e.DateReturn).HasColumnType("datetime");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<vwAvailableBook>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vwAvailableBooks");

            entity.Property(e => e.BookTitle)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.DateExpectedReturn)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ISBN)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}